-- ============================================================
-- Keywords importadas desde PalabrasClave_PorLineaNegocio.xlsx
-- Total: 226 keywords
-- Ejecutar en: https://supabase.valparaiso.cafe → SQL Editor
-- ============================================================

INSERT INTO matec_radar.palabras_clave_por_linea
  (sub_linea_id, palabra, idioma, tipo, peso, activo)
VALUES
  (1, 'expansión de aeropuerto', 'es', 'senal', 2, TRUE),
  (1, 'ampliación de aeropuerto', 'es', 'senal', 2, TRUE),
  (1, 'modernización de aeropuerto', 'es', 'senal', 2, TRUE),
  (1, 'desarrollo de aeropuerto', 'en', 'senal', 2, TRUE),
  (1, 'inversión en aeropuerto', 'es', 'senal', 2, TRUE),
  (1, 'construcción de aeropuerto', 'es', 'senal', 2, TRUE),
  (1, 'nuevo aeropuerto internacional', 'en', 'senal', 2, TRUE),
  (1, 'ampliación de capacidad aeroportuaria', 'es', 'senal', 2, TRUE),
  (1, 'plan maestro aeropuerto', 'en', 'senal', 2, TRUE),
  (1, 'master plan aeropuerto', 'en', 'senal', 2, TRUE),
  (1, 'concesión aeroportuaria', 'es', 'senal', 2, TRUE),
  (1, 'licitación aeropuerto', 'es', 'senal', 2, TRUE),
  (1, 'expansión de terminal aeroportuaria', 'es', 'senal', 2, TRUE),
  (1, 'ampliación de terminal de pasajeros', 'es', 'senal', 2, TRUE),
  (1, 'construcción de terminal aeroportuaria', 'es', 'senal', 2, TRUE),
  (1, 'nueva terminal de pasajeros', 'en', 'senal', 2, TRUE),
  (1, 'modernización de terminal aérea', 'es', 'senal', 2, TRUE),
  (1, 'renovación de terminal aeroportuaria', 'es', 'senal', 2, TRUE),
  (1, 'expansión del edificio terminal', 'es', 'senal', 2, TRUE),
  (1, 'inversión en terminal aeroportuaria', 'es', 'senal', 2, TRUE),
  (1, 'aumento de capacidad de pasajeros aeropuerto', 'en', 'senal', 2, TRUE),
  (1, 'sistema de manejo de equipaje', 'en', 'producto', 1, TRUE),
  (1, 'BHS aeropuerto', 'en', 'producto', 1, TRUE),
  (1, 'modernización del BHS', 'es', 'producto', 1, TRUE),
  (1, 'ampliación del sistema de equipaje', 'es', 'producto', 1, TRUE),
  (1, 'automatización de equipaje aeropuerto', 'es', 'producto', 1, TRUE),
  (1, 'reemplazo de sistema de equipaje', 'en', 'producto', 1, TRUE),
  (1, 'sistema de clasificación de equipaje', 'es', 'producto', 1, TRUE),
  (1, 'transporte de equipaje aeropuerto', 'en', 'producto', 1, TRUE),
  (1, 'carruseles de equipaje aeropuerto', 'en', 'producto', 1, TRUE),
  (1, 'sistema de reclamo de equipaje', 'en', 'producto', 1, TRUE),
  (1, 'self bag drop', 'en', 'producto', 1, TRUE),
  (1, 'baggage handling system', 'en', 'producto', 1, TRUE),
  (1, 'airport BHS upgrade', 'en', 'producto', 1, TRUE),
  (1, 'baggage handling automation', 'en', 'producto', 1, TRUE),
  (1, 'baggage system modernization', 'en', 'producto', 1, TRUE),
  (1, 'baggage claim system airport', 'en', 'producto', 1, TRUE),
  (1, 'self bag drop system', 'en', 'producto', 1, TRUE),
  (1, 'automatización de check in aeropuerto', 'es', 'senal', 1, TRUE),
  (1, 'kioscos de check in aeropuerto', 'en', 'senal', 1, TRUE),
  (1, 'automatización de facturación de equipaje', 'es', 'senal', 1, TRUE),
  (1, 'check in automático aeropuerto', 'es', 'senal', 1, TRUE),
  (1, 'biometría en aeropuerto check in', 'es', 'senal', 1, TRUE),
  (1, 'automatización de procesos aeroportuarios', 'es', 'senal', 1, TRUE),
  (1, 'automated check in airport', 'en', 'senal', 1, TRUE),
  (1, 'airport passenger automation', 'en', 'senal', 1, TRUE),
  (1, 'biometric airport check in', 'en', 'senal', 1, TRUE),
  (1, 'airport security checkpoint upgrade', 'en', 'senal', 1, TRUE),
  (1, 'baggage screening system airport', 'en', 'senal', 1, TRUE),
  (1, 'EDS standard 3 airport', 'en', 'senal', 1, TRUE),
  (1, 'EDS aeropuerto', 'en', 'senal', 1, TRUE),
  (1, 'sistema de inspección de equipaje', 'es', 'senal', 1, TRUE),
  (1, 'modernización de seguridad aeropuerto', 'es', 'senal', 1, TRUE),
  (1, 'expansión checkpoint aeropuerto', 'es', 'senal', 1, TRUE),
  (1, 'airport expansion', 'en', 'senal', 1, TRUE),
  (1, 'airport modernization', 'en', 'senal', 1, TRUE),
  (1, 'airport development project', 'en', 'senal', 1, TRUE),
  (1, 'airport infrastructure investment', 'en', 'senal', 1, TRUE),
  (1, 'airport capacity expansion', 'en', 'senal', 1, TRUE),
  (1, 'airport master plan', 'en', 'senal', 1, TRUE),
  (1, 'airport concession project', 'en', 'senal', 1, TRUE),
  (1, 'airport terminal expansion', 'en', 'senal', 1, TRUE),
  (1, 'new passenger terminal', 'en', 'senal', 1, TRUE),
  (1, 'passenger terminal construction', 'en', 'senal', 1, TRUE),
  (1, 'airport terminal modernization', 'en', 'senal', 1, TRUE),
  (1, 'LATAM airport expansion', 'en', 'senal', 1, TRUE),
  (1, 'Latin America airport investment', 'en', 'senal', 1, TRUE),
  (1, 'Caribbean airport infrastructure', 'en', 'senal', 1, TRUE),
  (1, 'ACI (Airports Council International)', 'ht', 'senal', 1, TRUE),
  (1, 'IATA', 'ht', 'senal', 1, TRUE),
  (1, 'ACI-LAC (Americas)', 'ht', 'senal', 1, TRUE),
  (1, 'SCT Mexico (licitaciones)', 'ht', 'senal', 1, TRUE),
  (1, 'Aerocivil Colombia', 'ht', 'senal', 1, TRUE),
  (1, 'ANAC Brasil', 'ht', 'senal', 1, TRUE),
  (1, 'Portales licitaciones MX', 'ht', 'senal', 1, TRUE),
  (1, 'SECOP Colombia', 'ht', 'senal', 1, TRUE),
  (1, 'Mercado Público Chile', 'ht', 'senal', 1, TRUE),
  (1, 'Colombia Compra', 'ht', 'senal', 1, TRUE),
  (2, 'terminal de carga aérea', 'es', 'senal', 2, TRUE),
  (2, 'expansión de terminal de carga aérea', 'es', 'senal', 2, TRUE),
  (2, 'construcción de terminal de carga aérea', 'es', 'senal', 2, TRUE),
  (2, 'modernización de terminal de carga aérea', 'es', 'senal', 2, TRUE),
  (2, 'infraestructura de carga aeroportuaria', 'en', 'senal', 2, TRUE),
  (2, 'hub de carga aérea', 'es', 'senal', 2, TRUE),
  (2, 'centro logístico aeroportuario', 'es', 'senal', 2, TRUE),
  (2, 'expansión de operaciones de carga aérea', 'es', 'senal', 2, TRUE),
  (2, 'inversión en infraestructura de carga aérea', 'es', 'senal', 2, TRUE),
  (2, 'desarrollo de infraestructura logística aeroportuaria', 'es', 'senal', 2, TRUE),
  (2, 'logística de carga aeroportuaria', 'es', 'producto', 1, TRUE),
  (2, 'plataforma logística aeroportuaria', 'es', 'producto', 1, TRUE),
  (2, 'terminal logística aeroportuaria', 'es', 'producto', 1, TRUE),
  (2, 'zona de carga aeropuerto', 'en', 'producto', 1, TRUE),
  (2, 'infraestructura logística en aeropuerto', 'es', 'producto', 1, TRUE),
  (2, 'centro de distribución aeroportuario', 'es', 'producto', 1, TRUE),
  (2, 'terminal de carga internacional aeropuerto', 'en', 'producto', 1, TRUE),
  (2, 'expansión zona cargo aeropuerto', 'es', 'producto', 1, TRUE),
  (2, 'automatización de terminal de carga aérea', 'es', 'producto', 1, TRUE),
  (2, 'cargo handling system airport', 'en', 'producto', 1, TRUE),
  (2, 'air cargo terminal expansion', 'en', 'producto', 1, TRUE),
  (2, 'airport cargo infrastructure', 'en', 'producto', 1, TRUE),
  (2, 'air cargo hub development', 'en', 'producto', 1, TRUE),
  (4, 'expansión de planta industrial', 'es', 'senal', 2, TRUE),
  (4, 'nueva planta industrial', 'en', 'senal', 2, TRUE),
  (4, 'inversión en planta de producción', 'es', 'senal', 2, TRUE),
  (4, 'ampliación de capacidad productiva', 'es', 'senal', 2, TRUE),
  (4, 'proyecto de automatización industrial', 'es', 'senal', 2, TRUE),
  (4, 'modernización de línea de producción', 'es', 'senal', 2, TRUE),
  (4, 'proyecto de ingeniería industrial', 'es', 'senal', 2, TRUE),
  (4, 'transportadores industriales', 'en', 'producto', 1, TRUE),
  (4, 'bandas transportadoras industriales', 'en', 'producto', 1, TRUE),
  (4, 'rodillos transportadores', 'en', 'producto', 1, TRUE),
  (4, 'sistemas de paletizado', 'en', 'producto', 1, TRUE),
  (4, 'paletizado automático', 'es', 'producto', 1, TRUE),
  (4, 'robot paletizador', 'en', 'producto', 1, TRUE),
  (4, 'encajonado automático', 'es', 'producto', 1, TRUE),
  (4, 'formado de cajas automático', 'es', 'producto', 1, TRUE),
  (4, 'sellado de cajas automático', 'es', 'producto', 1, TRUE),
  (4, 'línea de embalaje', 'es', 'producto', 1, TRUE),
  (4, 'sistemas de transporte interno', 'en', 'producto', 1, TRUE),
  (4, 'manejo de materiales industrial', 'en', 'producto', 1, TRUE),
  (4, 'automatización de final de línea', 'es', 'senal', 1, TRUE),
  (4, 'automatización de empaque', 'es', 'senal', 1, TRUE),
  (4, 'línea de empaque automatizada', 'es', 'senal', 1, TRUE),
  (4, 'sistemas de empaque industrial', 'en', 'senal', 1, TRUE),
  (4, 'automatización de fin de línea', 'es', 'senal', 1, TRUE),
  (4, 'integración de sistemas logísticos', 'es', 'senal', 1, TRUE),
  (4, 'optimización de procesos productivos', 'es', 'senal', 1, TRUE),
  (4, 'eficiencia operativa en planta', 'en', 'senal', 1, TRUE),
  (4, 'mejora de productividad industrial', 'en', 'senal', 1, TRUE),
  (4, 'automatización de procesos logísticos', 'es', 'senal', 1, TRUE),
  (4, 'sistemas intralogísticos', 'es', 'sector', 1, TRUE),
  (4, 'centro de distribución automatizado', 'es', 'sector', 1, TRUE),
  (4, 'automatización de almacenes', 'es', 'sector', 1, TRUE),
  (4, 'logística interna automatizada', 'es', 'sector', 1, TRUE),
  (4, 'proyectos CAPEX industrial', 'en', 'senal', 1, TRUE),
  (4, 'licitación industrial automatización', 'es', 'senal', 1, TRUE),
  (5, 'expansión planta motocicletas', 'es', 'senal', 2, TRUE),
  (5, 'inversión en planta automotriz motos', 'es', 'senal', 2, TRUE),
  (5, 'ampliación de capacidad producción motocicletas', 'es', 'senal', 2, TRUE),
  (5, 'proyecto industrial ensambladora de motos', 'en', 'senal', 2, TRUE),
  (5, 'modernización de línea de producción automotriz', 'es', 'senal', 2, TRUE),
  (5, 'ensamble de motocicletas', 'en', 'producto', 1, TRUE),
  (5, 'línea de ensamble de motos', 'es', 'producto', 1, TRUE),
  (5, 'línea de producción de motocicletas', 'es', 'producto', 1, TRUE),
  (5, 'planta de ensamblaje de motos', 'en', 'producto', 1, TRUE),
  (5, 'fabricación de motocicletas', 'es', 'producto', 1, TRUE),
  (5, 'proceso de ensamblaje automotriz', 'en', 'producto', 1, TRUE),
  (5, 'final de línea ensamblaje motocicletas', 'es', 'producto', 1, TRUE),
  (5, 'salida de línea de producción motos', 'es', 'producto', 1, TRUE),
  (5, 'control de calidad final motocicletas', 'en', 'producto', 1, TRUE),
  (5, 'flujo de materiales en ensamble de motos', 'en', 'senal', 1, TRUE),
  (5, 'transporte interno en planta automotriz', 'en', 'senal', 1, TRUE),
  (5, 'sistemas de transporte para ensamble', 'en', 'senal', 1, TRUE),
  (5, 'abastecimiento de línea de producción', 'es', 'senal', 1, TRUE),
  (5, 'logística interna en ensamblaje', 'es', 'senal', 1, TRUE),
  (5, 'automatización de ensamble de motos', 'es', 'senal', 1, TRUE),
  (5, 'automatización industrial automotriz', 'es', 'senal', 1, TRUE),
  (5, 'robotización en ensamblaje', 'es', 'senal', 1, TRUE),
  (6, 'nuevo centro de distribución México', 'es', 'senal', 1, TRUE),
  (6, 'nuevo CEDIS México', 'es', 'senal', 1, TRUE),
  (6, 'nuevo centro logístico México', 'es', 'senal', 1, TRUE),
  (6, 'expansión planta México', 'es', 'senal', 1, TRUE),
  (6, 'inversión industrial México', 'es', 'senal', 1, TRUE),
  (6, 'parque logístico México', 'es', 'senal', 1, TRUE),
  (6, 'hub logístico México', 'es', 'senal', 1, TRUE),
  (6, 'nuevo parque industrial México', 'es', 'senal', 1, TRUE),
  (6, 'expansión logística México', 'es', 'senal', 1, TRUE),
  (6, 'nueva planta industrial México', 'es', 'senal', 1, TRUE),
  (6, 'nuevo centro de distribución Colombia', 'es', 'senal', 1, TRUE),
  (6, 'nuevo CEDI Colombia', 'en', 'senal', 1, TRUE),
  (6, 'nuevo centro logístico Colombia', 'es', 'senal', 1, TRUE),
  (6, 'expansión planta Colombia', 'es', 'senal', 1, TRUE),
  (6, 'inversión industrial Colombia', 'es', 'senal', 1, TRUE),
  (6, 'parque logístico Colombia', 'es', 'senal', 1, TRUE),
  (6, 'hub logístico Colombia', 'es', 'senal', 1, TRUE),
  (6, 'nuevo parque industrial Colombia', 'en', 'senal', 1, TRUE),
  (6, 'expansión logística Colombia', 'es', 'senal', 1, TRUE),
  (6, 'nueva planta industrial Colombia', 'en', 'senal', 1, TRUE),
  (6, 'HSE industrial', 'en', 'senal', 1, TRUE),
  (6, 'EHS planta industrial', 'en', 'senal', 1, TRUE),
  (6, 'seguridad industrial planta', 'en', 'senal', 1, TRUE),
  (6, 'SHE manufactura', 'en', 'senal', 1, TRUE),
  (6, 'gestión de riesgos industrial', 'es', 'senal', 1, TRUE),
  (6, 'cumplimiento normativo HSE', 'en', 'senal', 1, TRUE),
  (6, 'reducción de accidentalidad industrial', 'es', 'senal', 1, TRUE),
  (6, 'optimización de centros de distribución', 'es', 'sector', 1, TRUE),
  (6, 'CEDIS automatizado', 'en', 'sector', 1, TRUE),
  (6, 'bodega automatizada', 'en', 'sector', 1, TRUE),
  (6, 'warehouse management', 'en', 'sector', 1, TRUE),
  (6, 'WMS implementación', 'es', 'sector', 1, TRUE),
  (6, 'logística de última milla industrial', 'es', 'sector', 1, TRUE),
  (6, 'distribución industrial LATAM', 'es', 'sector', 1, TRUE),
  (3, 'nueva planta corrugadora', 'en', 'senal', 2, TRUE),
  (3, 'expansión planta cartonera', 'es', 'senal', 2, TRUE),
  (3, 'adquisición planta de cartón', 'es', 'senal', 2, TRUE),
  (3, 'nueva máquina corrugadora', 'es', 'senal', 2, TRUE),
  (3, 'nueva máquina de conversión', 'es', 'senal', 2, TRUE),
  (3, 'nueva corrugadora', 'en', 'senal', 2, TRUE),
  (3, 'expansión', 'es', 'senal', 2, TRUE),
  (3, 'adquisición', 'es', 'senal', 2, TRUE),
  (3, 'máquina corrugadora', 'es', 'producto', 1, TRUE),
  (3, 'línea de corrugado', 'es', 'producto', 1, TRUE),
  (3, 'planta de conversión', 'es', 'producto', 1, TRUE),
  (3, 'máquina de troquelado', 'es', 'producto', 1, TRUE),
  (3, 'equipo de impresión flexográfica', 'es', 'producto', 1, TRUE),
  (3, 'línea de manufactura de cajas', 'es', 'producto', 1, TRUE),
  (3, 'sistema de manejo de papel', 'en', 'producto', 1, TRUE),
  (3, 'corrugated packaging expansion', 'en', 'sector', 1, TRUE),
  (3, 'new corrugating machine', 'en', 'sector', 1, TRUE),
  (3, 'box plant investment', 'en', 'sector', 1, TRUE),
  (3, 'carton plant expansion', 'en', 'sector', 1, TRUE),
  (3, 'paper packaging LATAM', 'en', 'sector', 1, TRUE),
  (3, 'new kraft liner machine', 'en', 'sector', 1, TRUE),
  (3, 'corrugated board plant', 'en', 'sector', 1, TRUE),
  (3, 'box manufacturing investment', 'en', 'sector', 1, TRUE),
  (3, 'packaging plant expansion Latin America', 'en', 'sector', 1, TRUE),
  (3, 'new converting line', 'en', 'sector', 1, TRUE),
  (3, 'AICC Mexico', 'ht', 'senal', 1, TRUE),
  (3, 'AICC North America', 'ht', 'senal', 1, TRUE),
  (3, 'ACCCSA', 'ht', 'senal', 1, TRUE),
  (3, 'AMEXICORR', 'ht', 'senal', 1, TRUE),
  (3, 'TAPPI', 'ht', 'senal', 1, TRUE),
  (3, 'ANFEC', 'ht', 'senal', 1, TRUE),
  (3, 'FEFCO', 'ht', 'senal', 1, TRUE),
  (3, 'LATAMCORR', 'ht', 'senal', 1, TRUE),
  (3, 'CORRUGA EXPERT', 'ht', 'senal', 1, TRUE)
ON CONFLICT (sub_linea_id, palabra, idioma, tipo)
DO UPDATE SET peso = EXCLUDED.peso, activo = TRUE;

-- Verificación
SELECT sl.codigo, COUNT(*) as total
FROM matec_radar.palabras_clave_por_linea p
JOIN matec_radar.sub_lineas_negocio sl ON p.sub_linea_id = sl.id
WHERE p.activo = TRUE
GROUP BY sl.codigo ORDER BY sl.codigo;
